AllCops:
  NewCops: enable

Metrics/MethodLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
